# Generated by Django 4.1.1 on 2022-09-07 17:47

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('address_details', jsonfield.fields.JSONField()),
                ('house_num', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('workExperience', jsonfield.fields.JSONField()),
                ('companyName', models.CharField(blank=True, max_length=100)),
                ('fromDate', models.CharField(blank=True, max_length=100)),
                ('toDate', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('qualifications', jsonfield.fields.JSONField()),
                ('qualificationName', models.CharField(blank=True, max_length=100)),
                ('percentage', models.FloatField(blank=True, max_length=1000)),
                ('projects', jsonfield.fields.JSONField()),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
