# Generated by Django 4.1.1 on 2022-09-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_App', '0004_alter_customer_data_address_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_data',
            name='quaToDate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer_data',
            name='quafromDate',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
