# Generated by Django 4.1.1 on 2022-09-08 23:02

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_App', '0005_customer_data_quatodate_customer_data_quafromdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_data',
            name='projects',
            field=jsonfield.fields.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer_data',
            name='qualifications',
            field=jsonfield.fields.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer_data',
            name='workExperience',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
