# Generated by Django 4.1.1 on 2022-09-08 23:23

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_App', '0006_alter_customer_data_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_data',
            name='projects',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='customer_data',
            name='qualifications',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='customer_data',
            name='workExperience',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
